/**
 * @fileoverview Default country configurations for ApplyPilot AI.
 * Provides system-level defaults for each supported country including
 * document labels, spelling styles, salary formats, visa requirements,
 * common job sources, and CV/cover letter generation rules.
 *
 * These configs are used to:
 * - Seed the country_configs database table
 * - Provide runtime defaults when creating new country preferences
 * - Drive document generation rules per country
 */

import type { CountryConfig } from '../types/country';

/**
 * Default configurations for all supported countries.
 * Each entry defines the rules and conventions for job applications
 * in that country.
 */
export const DEFAULT_COUNTRY_CONFIGS: CountryConfig[] = [
  {
    id: '00000000-0000-0000-0000-000000000001',
    country_name: 'United Kingdom',
    country_code: 'GB',
    currency: 'GBP',
    document_label: 'CV',
    default_language: 'English',
    spelling_style: 'british',
    salary_period: 'annual',
    visa_check_required: true,
    sponsorship_check_required: true,
    default_job_sources: [
      'LinkedIn',
      'Indeed',
      'Reed',
      'Totaljobs',
      'Guardian Jobs',
      'Civil Service Jobs',
      'NHS Jobs',
      'Glassdoor',
    ],
    cv_rules_json: {
      max_pages: 2,
      include_photo: false,
      include_date_of_birth: false,
      include_nationality: false,
      include_marital_status: false,
      format: 'reverse_chronological',
      tone: 'professional',
      spelling: 'british',
      address_format: 'city_only',
      notes: 'No personal details beyond name, email, phone, LinkedIn. Use action verbs. Quantify achievements.',
    },
    cover_letter_rules_json: {
      style: 'standard',
      max_words: 400,
      tone: 'professional_but_warm',
      greeting: 'Dear Hiring Manager',
      sign_off: 'Yours sincerely',
      paragraphs: 3,
      notes: 'Reference the specific role and company. Show enthusiasm. Link experience to requirements.',
    },
    flag_emoji: '\u{1F1EC}\u{1F1E7}',
    created_at: '',
    updated_at: '',
  },
  {
    id: '00000000-0000-0000-0000-000000000002',
    country_name: 'United States',
    country_code: 'US',
    currency: 'USD',
    document_label: 'Resume',
    default_language: 'English',
    spelling_style: 'american',
    salary_period: 'annual',
    visa_check_required: true,
    sponsorship_check_required: true,
    default_job_sources: [
      'LinkedIn',
      'Indeed',
      'Glassdoor',
      'ZipRecruiter',
      'Monster',
      'CareerBuilder',
      'USAJobs',
      'Dice',
    ],
    cv_rules_json: {
      max_pages: 1,
      include_photo: false,
      include_date_of_birth: false,
      include_nationality: false,
      include_marital_status: false,
      format: 'reverse_chronological',
      tone: 'action_oriented',
      spelling: 'american',
      address_format: 'city_state',
      notes: 'One page strongly preferred. Use strong action verbs. Quantify everything. No references section. ATS-friendly formatting.',
    },
    cover_letter_rules_json: {
      style: 'standard',
      max_words: 350,
      tone: 'confident_and_direct',
      greeting: 'Dear Hiring Manager',
      sign_off: 'Sincerely',
      paragraphs: 3,
      notes: 'Be concise and impactful. Lead with strongest qualification. Show cultural fit.',
    },
    flag_emoji: '\u{1F1FA}\u{1F1F8}',
    created_at: '',
    updated_at: '',
  },
  {
    id: '00000000-0000-0000-0000-000000000003',
    country_name: 'Canada',
    country_code: 'CA',
    currency: 'CAD',
    document_label: 'Resume',
    default_language: 'English',
    spelling_style: 'canadian',
    salary_period: 'annual',
    visa_check_required: true,
    sponsorship_check_required: true,
    default_job_sources: [
      'LinkedIn',
      'Indeed',
      'Glassdoor',
      'Job Bank',
      'Workopolis',
      'Monster',
      'Eluta',
      'Canadian Government Jobs',
    ],
    cv_rules_json: {
      max_pages: 2,
      include_photo: false,
      include_date_of_birth: false,
      include_nationality: false,
      include_marital_status: false,
      format: 'reverse_chronological',
      tone: 'professional',
      spelling: 'canadian',
      address_format: 'city_province',
      notes: 'Similar to US resume but can be 2 pages. Canadian spelling (colour, centre). Include LinkedIn URL. Bilingual roles may need French version.',
    },
    cover_letter_rules_json: {
      style: 'standard',
      max_words: 400,
      tone: 'professional_and_friendly',
      greeting: 'Dear Hiring Manager',
      sign_off: 'Sincerely',
      paragraphs: 3,
      notes: 'Reference Canadian experience if applicable. Mention work authorization status if relevant.',
    },
    flag_emoji: '\u{1F1E8}\u{1F1E6}',
    created_at: '',
    updated_at: '',
  },
  {
    id: '00000000-0000-0000-0000-000000000004',
    country_name: 'Germany',
    country_code: 'DE',
    currency: 'EUR',
    document_label: 'CV / Lebenslauf',
    default_language: 'German',
    spelling_style: 'british',
    salary_period: 'annual',
    visa_check_required: true,
    sponsorship_check_required: true,
    default_job_sources: [
      'LinkedIn',
      'Indeed',
      'StepStone',
      'XING',
      'Glassdoor',
      'Arbeitsagentur',
      'Karriere.de',
      'Monster',
    ],
    cv_rules_json: {
      max_pages: 2,
      include_photo: true,
      include_date_of_birth: true,
      include_nationality: true,
      include_marital_status: false,
      format: 'reverse_chronological',
      tone: 'formal',
      spelling: 'british',
      address_format: 'full_address',
      notes: 'Professional photo expected. Date of birth is common. Tabular/structured format preferred. Include all education including school. Sign and date the CV. Lebenslauf format for German-language applications.',
    },
    cover_letter_rules_json: {
      style: 'standard',
      max_words: 500,
      tone: 'formal_and_structured',
      greeting: 'Sehr geehrte Damen und Herren',
      sign_off: 'Mit freundlichen Gr\u00FC\u00DFen',
      paragraphs: 4,
      notes: 'Formal tone. Reference the exact position. Include salary expectations and earliest start date. For English roles, use formal British English.',
    },
    flag_emoji: '\u{1F1E9}\u{1F1EA}',
    created_at: '',
    updated_at: '',
  },
  {
    id: '00000000-0000-0000-0000-000000000005',
    country_name: 'Ireland',
    country_code: 'IE',
    currency: 'EUR',
    document_label: 'CV',
    default_language: 'English',
    spelling_style: 'british',
    salary_period: 'annual',
    visa_check_required: true,
    sponsorship_check_required: true,
    default_job_sources: [
      'LinkedIn',
      'Indeed',
      'IrishJobs.ie',
      'Jobs.ie',
      'Glassdoor',
      'PublicJobs.ie',
      'Monster',
      'Recruit Ireland',
    ],
    cv_rules_json: {
      max_pages: 2,
      include_photo: false,
      include_date_of_birth: false,
      include_nationality: false,
      include_marital_status: false,
      format: 'reverse_chronological',
      tone: 'professional',
      spelling: 'british',
      address_format: 'city_county',
      notes: 'Follow UK conventions. Irish spelling follows British English. No photo, no personal details. Two pages maximum.',
    },
    cover_letter_rules_json: {
      style: 'standard',
      max_words: 400,
      tone: 'professional_but_warm',
      greeting: 'Dear Hiring Manager',
      sign_off: 'Yours sincerely',
      paragraphs: 3,
      notes: 'Similar to UK style. Reference Irish market knowledge if applicable. Warm but professional tone.',
    },
    flag_emoji: '\u{1F1EE}\u{1F1EA}',
    created_at: '',
    updated_at: '',
  },
  {
    id: '00000000-0000-0000-0000-000000000006',
    country_name: 'Netherlands',
    country_code: 'NL',
    currency: 'EUR',
    document_label: 'CV',
    default_language: 'English',
    spelling_style: 'british',
    salary_period: 'annual',
    visa_check_required: true,
    sponsorship_check_required: true,
    default_job_sources: [
      'LinkedIn',
      'Indeed',
      'Glassdoor',
      'Nationale Vacaturebank',
      'Intermediair',
      'Undutchables',
      'Together Abroad',
      'IAmExpat',
    ],
    cv_rules_json: {
      max_pages: 2,
      include_photo: true,
      include_date_of_birth: true,
      include_nationality: true,
      include_marital_status: false,
      format: 'reverse_chronological',
      tone: 'direct_and_factual',
      spelling: 'british',
      address_format: 'city_only',
      notes: 'Photo is common but optional for international roles. Dutch CVs are direct and factual. Include date of birth and nationality. English is widely accepted for international roles.',
    },
    cover_letter_rules_json: {
      style: 'short',
      max_words: 350,
      tone: 'direct_and_enthusiastic',
      greeting: 'Dear Hiring Manager',
      sign_off: 'Kind regards',
      paragraphs: 3,
      notes: 'Dutch prefer directness. Keep it concise. Show genuine interest in the company. English cover letters are acceptable for international roles.',
    },
    flag_emoji: '\u{1F1F3}\u{1F1F1}',
    created_at: '',
    updated_at: '',
  },
  {
    id: '00000000-0000-0000-0000-000000000007',
    country_name: 'Australia',
    country_code: 'AU',
    currency: 'AUD',
    document_label: 'Resume',
    default_language: 'English',
    spelling_style: 'australian',
    salary_period: 'annual',
    visa_check_required: true,
    sponsorship_check_required: true,
    default_job_sources: [
      'LinkedIn',
      'Indeed',
      'Seek',
      'Glassdoor',
      'Jora',
      'CareerOne',
      'Australian Government Jobs',
      'Ethical Jobs',
    ],
    cv_rules_json: {
      max_pages: 3,
      include_photo: false,
      include_date_of_birth: false,
      include_nationality: false,
      include_marital_status: false,
      format: 'reverse_chronological',
      tone: 'professional_and_approachable',
      spelling: 'australian',
      address_format: 'city_state',
      notes: 'Up to 3 pages acceptable. Australian spelling (colour, organised). Include key selection criteria responses for government roles. No photo or personal details.',
    },
    cover_letter_rules_json: {
      style: 'standard',
      max_words: 450,
      tone: 'professional_and_approachable',
      greeting: 'Dear Hiring Manager',
      sign_off: 'Kind regards',
      paragraphs: 3,
      notes: 'Address key selection criteria if listed. Government roles may require a separate statement addressing each criterion. Professional but approachable tone.',
    },
    flag_emoji: '\u{1F1E6}\u{1F1FA}',
    created_at: '',
    updated_at: '',
  },
  {
    id: '00000000-0000-0000-0000-000000000008',
    country_name: 'Remote Global',
    country_code: 'REMOTE',
    currency: 'USD',
    document_label: 'Resume',
    default_language: 'English',
    spelling_style: 'american',
    salary_period: 'annual',
    visa_check_required: false,
    sponsorship_check_required: false,
    default_job_sources: [
      'LinkedIn',
      'Indeed',
      'We Work Remotely',
      'Remote.co',
      'FlexJobs',
      'AngelList',
      'Remotive',
      'Working Nomads',
    ],
    cv_rules_json: {
      max_pages: 2,
      include_photo: false,
      include_date_of_birth: false,
      include_nationality: false,
      include_marital_status: false,
      format: 'reverse_chronological',
      tone: 'action_oriented',
      spelling: 'american',
      address_format: 'timezone_only',
      notes: 'Focus on remote work experience. Highlight async communication skills. Mention timezone and overlap availability. American English as default for global roles.',
    },
    cover_letter_rules_json: {
      style: 'short',
      max_words: 300,
      tone: 'confident_and_direct',
      greeting: 'Hello',
      sign_off: 'Best regards',
      paragraphs: 3,
      notes: 'Emphasise remote work experience and self-management skills. Mention timezone flexibility. Keep it brief — remote companies value conciseness.',
    },
    flag_emoji: '\u{1F30D}',
    created_at: '',
    updated_at: '',
  },
];

/**
 * Retrieves the default configuration for a specific country by its code.
 *
 * @param code - ISO 3166-1 alpha-2 country code (or 'REMOTE')
 * @returns The matching CountryConfig, or undefined if not found
 *
 * @example
 * ```ts
 * const ukConfig = getCountryConfig('GB');
 * console.log(ukConfig?.document_label); // 'CV'
 * ```
 */
export function getCountryConfig(code: string): CountryConfig | undefined {
  return DEFAULT_COUNTRY_CONFIGS.find(
    (config) => config.country_code.toUpperCase() === code.toUpperCase()
  );
}
